# Docker-compose version
version: '3'

# Define the services/containers to be run
services:
      
  # Database
  database:
    # image to build container from
    image: mongo:4.1 
    ports:
      - "27018:27017"
    networks:
      - backend_network
  
  # Backend
  backend: 
    # directory of Dockerfile
    build: ./server
    ports:
      - "3000:3000"
    # link this service to database service
    links:
      - database 
    environment:
      - DB_HOST=database
    networks:
      - backend_network
    depends_on:
      - database
      
  # Frontend
  frontend:
    build: ./client
    ports:
      - "2000:2000"
    networks:
      - frontend_network

  # Proxy server
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network:
  backend_network: