# Docker-compose version
version: '3'

# Define the services/containers to be run
services:
      
  # Database
  database:
    # image to build container from
    image: mongo:4.1 
    ports:
      - "27018:27017"
    networks:
      - backend_network
  
  # Backend
  backend: 
    # directory of Dockerfile
    build: ./server
    ports:
      - "3000:3000"
    # link this service to database service
    links:
      - database 
    environment:
      - DB_HOST=database
    networks:
      - backend_network
    depends_on:
      - database

networks:
  backend_network: